const ADD_TO_CART_REQUEST = '@cart/ADD_REQUEST';
const ADD_TO_CART_SUCCESS = '@cart/ADD_SUCCESS';
const REMOVE_TO_CART = '@cart/REMOVE';
const UPDATE_AMOUNT_REQUEST = '@cart/UPDATE_REQUEST';
const UPDATE_AMOUNT_SUCCESS = '@cart/UPDATE_SUCCESS';

export {
    ADD_TO_CART_REQUEST,
    REMOVE_TO_CART,
    UPDATE_AMOUNT_REQUEST,
    ADD_TO_CART_SUCCESS,
    UPDATE_AMOUNT_SUCCESS
};
