const REMOVE_TO_CART_REQUEST = '@cart/REMOVE_TO_CART_REQUEST';
const REMOVE_UNIT_REQUEST = '@cart/REMOVE_UNIT_REQUEST'
const UPDATE_AMOUNT_REQUEST = '@cart/UPDATE_REQUEST';
const ADD_TO_CART_REQUEST = '@cart/ADD_REQUEST';

const REMOVE_TO_CART_SUCCESS = '@cart/REMOVE_SUCCESS';
const ADD_TO_CART_SUCCESS = '@cart/ADD_SUCCESS';
const UPDATE_AMOUNT_SUCCESS = '@cart/UPDATE_SUCCESS';
const REMOVE_UNIT_SUCCESS = '@cart/REMOVE_UNIT_SUCCESS';

export {
    ADD_TO_CART_REQUEST,
    REMOVE_TO_CART_SUCCESS,
    UPDATE_AMOUNT_REQUEST,
    ADD_TO_CART_SUCCESS,
    UPDATE_AMOUNT_SUCCESS,
    REMOVE_TO_CART_REQUEST,
    REMOVE_UNIT_REQUEST,
    REMOVE_UNIT_SUCCESS
};
